name: 부동산 모니터링

on:
  schedule:
    - cron: '0 23 * * *'   # 한국시간 08:00
    - cron: '0 11 * * *'   # 한국시간 20:00
  workflow_dispatch:         # 수동 실행

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Python 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 패키지 설치
        run: pip install requests

      - name: config.json 생성
        run: |
          cat > config.json << 'HEREDOC'
          {
            "api_key": "${{ secrets.API_KEY }}",
            "telegram": {
              "bot_token": "${{ secrets.TELEGRAM_BOT_TOKEN }}",
              "chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}"
            },
            "kakao_key": "${{ secrets.KAKAO_KEY }}",
            "filters": {
              "min_area": 59,
              "max_area": 84,
              "min_price": 0,
              "max_price": 60000,
              "min_floor": 1,
              "max_build_year": 9999,
              "min_households": 200
            },
            "regions": [
              {"name": "서울 강남구", "code": "11680", "sgg_name": "서울 강남구"},
              {"name": "서울 서초구", "code": "11650", "sgg_name": "서울 서초구"},
              {"name": "서울 송파구", "code": "11710", "sgg_name": "서울 송파구"},
              {"name": "서울 강동구", "code": "11740", "sgg_name": "서울 강동구"},
              {"name": "경기 과천시", "code": "41290", "sgg_name": "경기 과천시"},
              {"name": "경기 안양 만안구", "code": "41171", "sgg_name": "경기 안양시 만안구"},
              {"name": "경기 안양 동안구", "code": "41173", "sgg_name": "경기 안양시 동안구"},
              {"name": "경기 성남 수정구", "code": "41131", "sgg_name": "경기 성남시 수정구"},
              {"name": "성남 중원구", "code": "41133", "sgg_name": "경기 성남시 중원구"},
              {"name": "성남 분당구", "code": "41135", "sgg_name": "경기 성남시 분당구"},
              {"name": "경기 하남시", "code": "41450", "sgg_name": "경기 하남시"},
              {"name": "용인 수지구", "code": "41465", "sgg_name": "경기 용인시 수지구"},
              {"name": "용인 기흥구", "code": "41463", "sgg_name": "경기 용인시 기흥구"},
              {"name": "경기 광주시", "code": "41610", "sgg_name": "경기 광주시"}
            ],
            "schedule": {
              "run_times": ["08:00", "20:00"]
            }
          }
          HEREDOC

      - name: 모니터링 실행
        run: python main.py
